services:
  - type: web
    name: kill_trader_bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    environment:
      pythonVersion: 3.11.8
